##
## Copyright (c) 2022, Empa, Leonie Fierz, Aaron Bojarski, Ricardo Parreira da Silva, Sven Eggimann.
##
## This file is part of CESAR-P - Combined Energy Simulation And Retrofit written in Python
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU Affero General Public License as
## published by the Free Software Foundation, either version 3 of the
## License, or (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Affero General Public License for more details.
##
## You should have received a copy of the GNU Affero General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
##
## Contact: https://www.empa.ch/web/s313
##
OPERATION:
  # Parameters when using the FixedBuildingOperationFactory (same parameters and profiles for all buildings)
  # To enable FIXED operation parameters set config MANAGER -  BUILDING_OPERATION_FACTORY_CLASS to 
  # "cesarp.operation.fixed.FixedBuildingOperationFactory.FixedBuildingOperationFactory"
  # parameters starting with SCHED_ should point to a file with a yearly profile (without header, only one column)
  # parameters with suffix _PER_ZONE_AREA relate to m2 of floor area
  FIXED: 
    FLOOR_AREA_PER_PERSON: 25.64103 m**2
    SCHED_OCCUPANCY_PATH: "./ressources/mfh_nominal_occupancy.csv"
    SCHED_ACTIVITY_PATH: "./ressources/mfh_nominal_activity.csv"
    SCHED_APPLIANCES_PATH: "./ressources/mfh_nominal_appliances.csv"
    APPLIANCES_WATT_PER_ZONE_AREA: 6.4 W/m**2
    SCHED_LIGHTING_PATH: "./ressources/mfh_nominal_lighting.csv"
    LIGHTING_WATT_PER_ZONE_AREA: 10.3104 W/m**2
    SCHED_DHW_PATH: "./ressources/mfh_nominal_dhw.csv"
    DHW_WATTS_PER_ZONE_AREA: 4.216667 W/m**2
    SCHED_THERMOSTAT_HEATING: "./ressources/mfh_nominal_thermostat_heating.csv"
    SCHED_THERMOSTAT_COOLING: "./ressources/mfh_nominal_thermostat_cooling.csv"
    OUTDOOR_AIR_FLOW_PER_ZONE_FLOOR_AREA: 1.297222e-03 m**3/(s * m**2)
    SCHED_VENTILATION: "./ressources/mfh_nominal_ventilation.csv"
    SCHED_PROPS: # same properties are applied for all the above profile csv files
      NUM_OF_HOURS: 8760  # should always be 8760, as we do full-horizon simulation with hourly resolution in EnergyPlus
      SEPARATOR: ","
      NUM_OF_HEADER_ROWS: 0  # no header assumed
      DATA_COLUMN: 1  # we assume each profile in its own file with only one column

